<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Madoc platform'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet('//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
$userBar = $this->partial('common/user-bar', ['site' => $site]);
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
</head>

<?php echo $this->htmlElement('body'); ?>
<?php echo $userBar; ?>
<header>
    <?php if ($this->themeSetting('logo')): ?>
        <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
    <?php else: ?>
        <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
    <?php endif; ?>
    <div id="search">
        <?php echo $this->partial('common/search-form'); ?>
    </div>

    <nav>
        <?php
        echo $site->publicNav()->menu()->renderMenu(null, [
            'maxDepth' => $this->themeSetting('nav_depth') - 1
        ]);
        ?>
    </nav>
</header>
<main id="content" role="main">
    <?php print $this->content; ?>
</main>
<footer>
    <?php if ($footerContent = $this->themeSetting('footer')): ?>
        <?php echo $footerContent; ?>
    <?php else: ?>
        <?php echo $this->translate('Powered by Madoc Platform running on Omeka S'); ?>
    <?php endif; ?>
</footer>
<?php echo $this->headScript(); ?>
</body>
</html>
