version: "3"
services:
  # Internal services

  gateway:
    ports:
      - "8988:8080"

  madoc-ts:
    build:
      context: services/madoc-ts
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    volumes:
      - ./e2e/test-fixtures/certs:/home/node/app/openssl-certs
      - jwt:/home/node/app/service-jwt-responses
      - files:/home/node/app/omeka-files

  tasks-api: {}

  model-api: {}

  shared-postgres:
    volumes:
      - shared_postgres_data:/var/lib/postgresql/data
      - ./e2e/test-fixtures/postgres/default:/docker-entrypoint-initdb.d

  gateway-redis: {}

  config-service: {}

  storage-api:
    volumes:
      - storage-api:/home/node/app/files

  search: {}

  okra: {}

volumes:

  # Shared resources
  jwt: {}

  # Databases
  shared_postgres_data: {}

  # Files
  files: {}
  storage-api: {}
