version: "3"
services:
  madoc:
    build:
      context: services/madoc
    links:
      - madoc-database
    environment:
      - APP_ENV=${APP_ENV}
      - OMEKA__DATABASE_HOST=madoc-database
      - OMEKA__DATABASE_NAME=omeka_s
      - OMEKA__DATABASE_USER=omeka_s
      - OMEKA__DATABASE_PASSWORD=ci_db_password
      - OMEKA__DATABASE_PORT=3306
      - OMEKA__MAIN_SITE_DOMAIN=${MAIN_SITE_DOMAIN}
      - OMEKA__ELUCIDATE_URL=${ELUCIDATE_URL}
      - OMEKA__INTERNAL_URL=${OMEKA_INTERNAL_URL}
      - OMEKA__ANNOTATION_INDEXER=${ANNOTATION_INDEXER}
      - OMEKA__ELUCIDATE_PUBLIC_DOMAIN=${ELUCIDATE_PUBLIC_DOMAIN}
      - OMEKA__SEARCH_ELASTICSEARCH=search-elasticsearch:9200
      - OMEKA__ANNOTATION_ES_INDEX=jane-annotations
      - OMEKA__SEARCH_INDEXER=search-indexer:8000
    ports:
      - "8888:80"

  madoc-database:
    build:
      context: services/madoc-database
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=omeka_s
      - MYSQL_USER=omeka_s
      - MYSQL_PASSWORD=ci_db_password
      - MYSQL_PORT=3306

  annotation-server:
    container_name: madoc-annotation-server
    image: "garyttierneydi/elucidate-server:1.4.3-SNAPSHOT"
    links:
      - annotation-database:database
    environment:
      - DATABASE_USER=postgres
      - CATALINA_OPTS=-Ddb.url=jdbc:postgresql://database:5432/annotations -Ddb.user="postgres" -Ddb.password=$MYSQL_PASSWORD
    ports:
      - 8889:8080

  annotation-database:
    container_name: madoc-annotation-database
    image: "garyttierneydi/elucidate-database:1.4.3-SNAPSHOT"
    environment:
      - POSTGRES_DB=annotations
