version: "3"
services:
  omeka_ecosystem:
    build:
      context: services/madoc
    links:
      - mysql
    environment:
      - APP_ENV=PROD
      - OMEKA__DATABASE_HOST=omeka_db
      - OMEKA__DATABASE_NAME=${MYSQL_DATABASE}
      - OMEKA__DATABASE_USER=${MYSQL_USER}
      - OMEKA__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - OMEKA__DATABASE_PORT=${MYSQL_PORT}
      - OMEKA__MAIN_SITE_DOMAIN=http://localhost:8888/
      - OMEKA__ELUCIDATE_URL=elucidate-server:8080
      - OMEKA__ELUCIDATE_PUBLIC_DOMAIN=http://localhost:8888/
    ports:
      - "80:80"
    volumes:
      - /opt/omeka-files:/srv/omeka/files:Z

  mysql:
    container_name: omeka_db
    build:
      context: services/madoc-database
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - /opt/mysql_data:/var/lib/mysql:Z

  annotation-server:
    container_name: elucidate-server
    image: "garyttierneydi/elucidate-server:1.4.3-SNAPSHOT"
    links:
      - annotation-database:database
    environment:
      - DATABASE_USER=postgres
      - CATALINA_OPTS=-Ddb.url=jdbc:postgresql://database:5432/annotations -Ddb.user="postgres" -Ddb.password=$MYSQL_PASSWORD
    ports:
      - 8889:8080
  annotation-database:
    image: "garyttierneydi/elucidate-database:1.4.3-SNAPSHOT"
    environment:
      - POSTGRES_DB=annotations
