export const TABULAR_WIZARD_CAST_A_NET_ROWS = 5;
export const TABULAR_WIZARD_PREVIEW_SPLIT_TOTAL_HEIGHT = 760;
export const TABULAR_WIZARD_PREVIEW_SPLIT_GAP = 12;
export const TABULAR_WIZARD_PREVIEW_SPLIT_DIVIDER_HEIGHT = 18;
