/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `property` WRITE;
/*!40000 ALTER TABLE `property` DISABLE KEYS */;
INSERT INTO `property` VALUES (1,NULL,1,'title','Title','A name given to the resource.'),
(2,NULL,1,'creator','Creator','An entity primarily responsible for making the resource.'),
(3,NULL,1,'subject','Subject','The topic of the resource.'),
(4,NULL,1,'description','Description','An account of the resource.'),
(5,NULL,1,'publisher','Publisher','An entity responsible for making the resource available.'),
(6,NULL,1,'contributor','Contributor','An entity responsible for making contributions to the resource.'),
(7,NULL,1,'date','Date','A point or period of time associated with an event in the lifecycle of the resource.'),
(8,NULL,1,'type','Type','The nature or genre of the resource.'),
(9,NULL,1,'format','Format','The file format, physical medium, or dimensions of the resource.'),
(10,NULL,1,'identifier','Identifier','An unambiguous reference to the resource within a given context.'),
(11,NULL,1,'source','Source','A related resource from which the described resource is derived.'),
(12,NULL,1,'language','Language','A language of the resource.'),
(13,NULL,1,'relation','Relation','A related resource.'),
(14,NULL,1,'coverage','Coverage','The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant.'),
(15,NULL,1,'rights','Rights','Information about rights held in and over the resource.'),
(16,NULL,1,'audience','Audience','A class of entity for whom the resource is intended or useful.'),
(17,NULL,1,'alternative','Alternative Title','An alternative name for the resource.'),
(18,NULL,1,'tableOfContents','Table Of Contents','A list of subunits of the resource.'),
(19,NULL,1,'abstract','Abstract','A summary of the resource.'),
(20,NULL,1,'created','Date Created','Date of creation of the resource.'),
(21,NULL,1,'valid','Date Valid','Date (often a range) of validity of a resource.'),
(22,NULL,1,'available','Date Available','Date (often a range) that the resource became or will become available.'),
(23,NULL,1,'issued','Date Issued','Date of formal issuance (e.g., publication) of the resource.'),
(24,NULL,1,'modified','Date Modified','Date on which the resource was changed.'),
(25,NULL,1,'extent','Extent','The size or duration of the resource.'),
(26,NULL,1,'medium','Medium','The material or physical carrier of the resource.'),
(27,NULL,1,'isVersionOf','Is Version Of','A related resource of which the described resource is a version, edition, or adaptation.'),
(28,NULL,1,'hasVersion','Has Version','A related resource that is a version, edition, or adaptation of the described resource.'),
(29,NULL,1,'isReplacedBy','Is Replaced By','A related resource that supplants, displaces, or supersedes the described resource.'),
(30,NULL,1,'replaces','Replaces','A related resource that is supplanted, displaced, or superseded by the described resource.'),
(31,NULL,1,'isRequiredBy','Is Required By','A related resource that requires the described resource to support its function, delivery, or coherence.'),
(32,NULL,1,'requires','Requires','A related resource that is required by the described resource to support its function, delivery, or coherence.'),
(33,NULL,1,'isPartOf','Is Part Of','A related resource in which the described resource is physically or logically included.'),
(34,NULL,1,'hasPart','Has Part','A related resource that is included either physically or logically in the described resource.'),
(35,NULL,1,'isReferencedBy','Is Referenced By','A related resource that references, cites, or otherwise points to the described resource.'),
(36,NULL,1,'references','References','A related resource that is referenced, cited, or otherwise pointed to by the described resource.'),
(37,NULL,1,'isFormatOf','Is Format Of','A related resource that is substantially the same as the described resource, but in another format.'),
(38,NULL,1,'hasFormat','Has Format','A related resource that is substantially the same as the pre-existing described resource, but in another format.'),
(39,NULL,1,'conformsTo','Conforms To','An established standard to which the described resource conforms.'),
(40,NULL,1,'spatial','Spatial Coverage','Spatial characteristics of the resource.'),
(41,NULL,1,'temporal','Temporal Coverage','Temporal characteristics of the resource.'),
(42,NULL,1,'mediator','Mediator','An entity that mediates access to the resource and for whom the resource is intended or useful.'),
(43,NULL,1,'dateAccepted','Date Accepted','Date of acceptance of the resource.'),
(44,NULL,1,'dateCopyrighted','Date Copyrighted','Date of copyright.'),
(45,NULL,1,'dateSubmitted','Date Submitted','Date of submission of the resource.'),
(46,NULL,1,'educationLevel','Audience Education Level','A class of entity, defined in terms of progression through an educational or training context, for which the described resource is intended.'),
(47,NULL,1,'accessRights','Access Rights','Information about who can access the resource or an indication of its security status.'),
(48,NULL,1,'bibliographicCitation','Bibliographic Citation','A bibliographic reference for the resource.'),
(49,NULL,1,'license','License','A legal document giving official permission to do something with the resource.'),
(50,NULL,1,'rightsHolder','Rights Holder','A person or organization owning or managing rights over the resource.'),
(51,NULL,1,'provenance','Provenance','A statement of any changes in ownership and custody of the resource since its creation that are significant for its authenticity, integrity, and interpretation.'),
(52,NULL,1,'instructionalMethod','Instructional Method','A process, used to engender knowledge, attitudes and skills, that the described resource is designed to support.'),
(53,NULL,1,'accrualMethod','Accrual Method','The method by which items are added to a collection.'),
(54,NULL,1,'accrualPeriodicity','Accrual Periodicity','The frequency with which items are added to a collection.'),
(55,NULL,1,'accrualPolicy','Accrual Policy','The policy governing the addition of items to a collection.'),
(56,NULL,3,'affirmedBy','affirmedBy','A legal decision that affirms a ruling.'),
(57,NULL,3,'annotates','annotates','Critical or explanatory note for a Document.'),
(58,NULL,3,'authorList','list of authors','An ordered list of authors. Normally, this list is seen as a priority list that order authors by importance.'),
(59,NULL,3,'citedBy','cited by','Relates a document to another document that cites the\nfirst document.'),
(60,NULL,3,'cites','cites','Relates a document to another document that is cited\nby the first document as reference, comment, review, quotation or for\nanother purpose.'),
(61,NULL,3,'contributorList','list of contributors','An ordered list of contributors. Normally, this list is seen as a priority list that order contributors by importance.'),
(62,NULL,3,'court','court','A court associated with a legal document; for example, that which issues a decision.'),
(63,NULL,3,'degree','degree','The thesis degree.'),
(64,NULL,3,'director','director','A Film director.'),
(65,NULL,3,'distributor','distributor','Distributor of a document or a collection of documents.'),
(66,NULL,3,'editor','editor','A person having managerial and sometimes policy-making responsibility for the editorial part of a publishing firm or of a newspaper, magazine, or other publication.'),
(67,NULL,3,'editorList','list of editors','An ordered list of editors. Normally, this list is seen as a priority list that order editors by importance.'),
(68,NULL,3,'interviewee','interviewee','An agent that is interviewed by another agent.'),
(69,NULL,3,'interviewer','interviewer','An agent that interview another agent.'),
(70,NULL,3,'issuer','issuer','An entity responsible for issuing often informally published documents such as press releases, reports, etc.'),
(71,NULL,3,'organizer','organizer','The organizer of an event; includes conference organizers, but also government agencies or other bodies that are responsible for conducting hearings.'),
(72,NULL,3,'owner','owner','Owner of a document or a collection of documents.'),
(73,NULL,3,'performer','performer',NULL),
(74,NULL,3,'presentedAt','presented at','Relates a document to an event; for example, a paper to a conference.'),
(75,NULL,3,'presents','presents','Relates an event to associated documents; for example, conference to a paper.'),
(76,NULL,3,'producer','producer','Producer of a document or a collection of documents.'),
(77,NULL,3,'recipient','recipient','An agent that receives a communication document.'),
(78,NULL,3,'reproducedIn','reproducedIn','The resource in which another resource is reproduced.'),
(79,NULL,3,'reversedBy','reversedBy','A legal decision that reverses a ruling.'),
(80,NULL,3,'reviewOf','review of','Relates a review document to a reviewed thing (resource, item, etc.).'),
(81,NULL,3,'status','status','The publication status of (typically academic) content.'),
(82,NULL,3,'subsequentLegalDecision','subsequentLegalDecision','A legal decision on appeal that takes action on a case (affirming it, reversing it, etc.).'),
(83,NULL,3,'transcriptOf','transcript of','Relates a document to some transcribed original.'),
(84,NULL,3,'translationOf','translation of','Relates a translated document to the original document.'),
(85,NULL,3,'translator','translator','A person who translates written document from one language to another.'),
(86,NULL,3,'abstract','abstract','A summary of the resource.'),
(87,NULL,3,'argued','date argued','The date on which a legal case is argued before a court. Date is of format xsd:date'),
(88,NULL,3,'asin','asin',NULL),
(89,NULL,3,'chapter','chapter','An chapter number'),
(90,NULL,3,'coden','coden',NULL),
(91,NULL,3,'content','content','This property is for a plain-text rendering of the content of a Document. While the plain-text content of an entire document could be described by this property.'),
(92,NULL,3,'doi','doi',NULL),
(93,NULL,3,'eanucc13','eanucc13',NULL),
(94,NULL,3,'edition','edition','The name defining a special edition of a document. Normally its a literal value composed of a version number and words.'),
(95,NULL,3,'eissn','eissn',NULL),
(96,NULL,3,'gtin14','gtin14',NULL),
(97,NULL,3,'handle','handle',NULL),
(98,NULL,3,'identifier','identifier',NULL),
(99,NULL,3,'isbn','isbn',NULL),
(100,NULL,3,'isbn10','isbn10',NULL),
(101,NULL,3,'isbn13','isbn13',NULL),
(102,NULL,3,'issn','issn',NULL),
(103,NULL,3,'issue','issue','An issue number'),
(104,NULL,3,'lccn','lccn',NULL),
(105,NULL,3,'locator','locator','A description (often numeric) that locates an item within a containing document or collection.'),
(106,NULL,3,'numPages','number of pages','The number of pages contained in a document'),
(107,NULL,3,'numVolumes','number of volumes','The number of volumes contained in a collection of documents (usually a series, periodical, etc.).'),
(108,NULL,3,'number','number','A generic item or document number. Not to be confused with issue number.'),
(109,NULL,3,'oclcnum','oclcnum',NULL),
(110,NULL,3,'pageEnd','page end','Ending page number within a continuous page range.'),
(111,NULL,3,'pageStart','page start','Starting page number within a continuous page range.'),
(112,NULL,3,'pages','pages','A string of non-contiguous page spans that locate a Document within a Collection. Example: 23-25, 34, 54-56. For continuous page ranges, use the pageStart and pageEnd properties.'),
(113,NULL,3,'pmid','pmid',NULL),
(114,NULL,3,'prefixName','prefix name','The prefix of a name'),
(115,NULL,3,'section','section','A section number'),
(116,NULL,3,'shortDescription','shortDescription',NULL),
(117,NULL,3,'shortTitle','short title','The abbreviation of a title.'),
(118,NULL,3,'sici','sici',NULL),
(119,NULL,3,'suffixName','suffix name','The suffix of a name'),
(120,NULL,3,'upc','upc',NULL),
(121,NULL,3,'uri','uri','Universal Resource Identifier of a document'),
(122,NULL,3,'volume','volume','A volume number'),
(123,NULL,4,'mbox','personal mailbox','A  personal mailbox, ie. an Internet mailbox associated with exactly one owner, the first owner of this mailbox. This is a \'static inverse functional property\', in that  there is (across time and change) at most one individual that ever has any particular value for foaf:mbox.'),
(124,NULL,4,'mbox_sha1sum','sha1sum of a personal mailbox URI name','The sha1sum of the URI of an Internet mailbox associated with exactly one owner, the  first owner of the mailbox.'),
(125,NULL,4,'gender','gender','The gender of this Agent (typically but not necessarily \'male\' or \'female\').'),
(126,NULL,4,'geekcode','geekcode','A textual geekcode for this person, see http://www.geekcode.com/geek.html'),
(127,NULL,4,'dnaChecksum','DNA checksum','A checksum for the DNA of some thing. Joke.'),
(128,NULL,4,'sha1','sha1sum (hex)','A sha1sum hash, in hex.'),
(129,NULL,4,'based_near','based near','A location that something is based near, for some broadly human notion of near.'),
(130,NULL,4,'title','title','Title (Mr, Mrs, Ms, Dr. etc)'),
(131,NULL,4,'nick','nickname','A short informal nickname characterising an agent (includes login identifiers, IRC and other chat nicknames).'),
(132,NULL,4,'jabberID','jabber ID','A jabber ID for something.'),
(133,NULL,4,'aimChatID','AIM chat ID','An AIM chat ID'),
(134,NULL,4,'skypeID','Skype ID','A Skype ID'),
(135,NULL,4,'icqChatID','ICQ chat ID','An ICQ chat ID'),
(136,NULL,4,'yahooChatID','Yahoo chat ID','A Yahoo chat ID'),
(137,NULL,4,'msnChatID','MSN chat ID','An MSN chat ID'),
(138,NULL,4,'name','name','A name for some thing.'),
(139,NULL,4,'firstName','firstName','The first name of a person.'),
(140,NULL,4,'lastName','lastName','The last name of a person.'),
(141,NULL,4,'givenName','Given name','The given name of some person.'),
(142,NULL,4,'givenname','Given name','The given name of some person.'),
(143,NULL,4,'surname','Surname','The surname of some person.'),
(144,NULL,4,'family_name','family_name','The family name of some person.'),
(145,NULL,4,'familyName','familyName','The family name of some person.'),
(146,NULL,4,'phone','phone','A phone,  specified using fully qualified tel: URI scheme (refs: http://www.w3.org/Addressing/schemes.html#tel).'),
(147,NULL,4,'homepage','homepage','A homepage for some thing.'),
(148,NULL,4,'weblog','weblog','A weblog of some thing (whether person, group, company etc.).'),
(149,NULL,4,'openid','openid','An OpenID for an Agent.'),
(150,NULL,4,'tipjar','tipjar','A tipjar document for this agent, describing means for payment and reward.'),
(151,NULL,4,'plan','plan','A .plan comment, in the tradition of finger and .plan files.'),
(152,NULL,4,'made','made','Something that was made by this agent.'),
(153,NULL,4,'maker','maker','An agent that  made this thing.'),
(154,NULL,4,'img','image','An image that can be used to represent some thing (ie. those depictions which are particularly representative of something, eg. ones photo on a homepage).'),
(155,NULL,4,'depiction','depiction','A depiction of some thing.'),
(156,NULL,4,'depicts','depicts','A thing depicted in this representation.'),
(157,NULL,4,'thumbnail','thumbnail','A derived thumbnail image.'),
(158,NULL,4,'myersBriggs','myersBriggs','A Myers Briggs (MBTI) personality classification.'),
(159,NULL,4,'workplaceHomepage','workplace homepage','A workplace homepage of some person; the homepage of an organization they work for.'),
(160,NULL,4,'workInfoHomepage','work info homepage','A work info homepage of some person; a page about their work for some organization.'),
(161,NULL,4,'schoolHomepage','schoolHomepage','A homepage of a school attended by the person.'),
(162,NULL,4,'knows','knows','A person known by this person (indicating some level of reciprocated interaction between the parties).'),
(163,NULL,4,'interest','interest','A page about a topic of interest to this person.'),
(164,NULL,4,'topic_interest','topic_interest','A thing of interest to this person.'),
(165,NULL,4,'publications','publications','A link to the publications of this person.'),
(166,NULL,4,'currentProject','current project','A current project this person works on.'),
(167,NULL,4,'pastProject','past project','A project this person has previously worked on.'),
(168,NULL,4,'fundedBy','funded by','An organization funding a project or person.'),
(169,NULL,4,'logo','logo','A logo representing some thing.'),
(170,NULL,4,'topic','topic','A topic of some page or document.'),
(171,NULL,4,'primaryTopic','primary topic','The primary topic of some page or document.'),
(172,NULL,4,'focus','focus','The underlying or \'focal\' entity associated with some SKOS-described concept.'),
(173,NULL,4,'isPrimaryTopicOf','is primary topic of','A document that this thing is the primary topic of.'),
(174,NULL,4,'page','page','A page or document about this thing.'),
(175,NULL,4,'theme','theme','A theme.'),
(176,NULL,4,'account','account','Indicates an account held by this agent.'),
(177,NULL,4,'holdsAccount','account','Indicates an account held by this agent.'),
(178,NULL,4,'accountServiceHomepage','account service homepage','Indicates a homepage of the service provide for this online account.'),
(179,NULL,4,'accountName','account name','Indicates the name (identifier) associated with this online account.'),
(180,NULL,4,'member','member','Indicates a member of a Group'),
(181,NULL,4,'membershipClass','membershipClass','Indicates the class of individuals that are a member of a Group'),
(182,NULL,4,'birthday','birthday','The birthday of this Agent, represented in mm-dd string form, eg. \'12-31\'.'),
(183,NULL,4,'age','age','The age in years of some agent.'),
(184,NULL,4,'status','status','A string expressing what the user is happy for the general public (normally) to know about their current activity.'),
(185,1,5,'uiInputType','uiInputType','Defines which user input control is rendered in a crowd-sourcing system, for capturing the value of an annotation. For example: textbox, listbox, dropdown. Options are defined by the Madoc vocabulary.'),
(186,1,5,'uiInputDefaultValue','uiInputDefaultValue','Provides default value for any input control.'),
(187,1,5,'uiInputOptions','uiInputOptions','Provides options refining the rendering of an input control, such as values for a drop-down. '),
(188,1,5,'uiSelectorType','uiSelectorType','Defines which user input control is rendered in a crowd-sourcing system, for selecting the target of an annotation.'),
(189,1,5,'uiSelectorValue','uiSelectorValue','Defines which value is preset for a user input control as rendered in a crowd-sourcing system, e.g. preset XYWH coordinates for a box, or preset XY coordinates for a pointer.'),
(190,1,5,'uiComponent','uiComponent','Provides a hint for which annotation studio component should load the annotation: resource provider; transcription; bookmarking; flagging; tagging, etc.'),
(191,1,5,'externalResourceModel','externalResourceModel','Dereference to return a description, model, or schema for the creation of an external resource from captured content.'),
(192,1,5,'uiGroup','uiGroup','Defines how a group of UI input elements should be rendered as a group.'),
(193,1,5,'uiFormGroup','uiFormGroup','Defines a named form group of UI input elements which should be rendered as a group (if uiGroup is set to form).'),
(194,1,5,'uiMultiple','uiMultiple','Boolean: defines whether a particular UI group or element can be used multiple times, for example, if tagging an image with two different people.'),
(195,1,5,'uiRequired','uiRequired','Boolean: defines whether a particular UI group or element MUST have a value.'),
(196,1,5,'uiHidden','uiHidden','Boolean: defines whether a particular UI group or element is displayed in the UI.'),
(197,1,5,'uiChoice','uiChoice','Boolean: defines whether a particular UI group is a choice, i.e. do not render all of these together, provide a choice between them.'),
(198,1,5,'derivedAnnoCombine','derivedAnnoCombine','Boolean: defines whether a particular set of putative annotations are to be combined into multiple annotation bodies in the same annotation (True), or stored as separate annotations (False).'),
(199,1,5,'derivedAnnoSerialize','derivedAnnoSerialize','Boolean: defines whether an annotation body or set of annotation bodies should be stored as a serialized TextualBody, i.e. as a string.'),
(200,1,5,'derivedAnnoExternalize','derivedAnnoExternalize','Boolean: defines whether an annotation body or set of annotation bodies should be used to generate an external resource, for example a topic page in a CMS system, which should be linked as the source of the annotation.'),
(201,1,5,'derivedAnnoHumanReadable','derivedAnnoHumanReadable','Boolean: defines whether an annotation body or set of annotation bodies should be converted to human readable plain text as a separate annotation body.'),
(202,1,5,'derivedAnnoMotivatedBy','derivedAnnoMotivatedBy','The relationship between the derived Annotation produced from this user input, and a Motivation that describes the reason for the Annotations creation.'),
(203,1,5,'derivedAnnoBodyPurpose','derivedAnnoBodyPurpose','The purpose served by the resource in the body of the derived Annotation.'),
(204,1,5,'derivedAnnoBodyFormat','derivedAnnoBodyFormat','The format of the resource in the body of the derived Annotation (e.g. text/plain, application/html).'),
(205,1,5,'derivedAnnoBodyLabelParts','derivedAnnoBodyLabelParts','Field or fields in the model to concatenate to produce the label for the annotation body.'),
(206,1,5,'derivedAnnoBodyType','derivedAnnoBodyType','The type of the resource in the body of the derived Annotation (e.g. TextualBody, ExternalResource, etc.).'),
(207,1,6,'textbox','textbox','UI: Render a TEXTBOX to capture input for value of annotation body.'),
(208,1,6,'hiddenvalue','hiddenvalue','UI: Hidden form field which can carry values.'),
(209,1,6,'textarea','textarea','UI: Render a TEXTAREA to capture input for value of annotation body.'),
(210,1,6,'listbox','listbox','UI: Render a DROPDOWN LIST to capture input for value of annotation body.'),
(211,1,6,'dropdown','dropdown','UI: Render a DROPDOWN LIST to capture input for value of annotation body.'),
(212,1,6,'combobox','combobox','UI: Render a COMBOBOX to capture input for value of annotation body.'),
(213,1,6,'datepicker','datepicker','UI: Render a DATE PICKER to capture calendar input for value of annotation body.'),
(214,1,6,'mappicker','mappicker','UI: Render a MAPPICKER to capture lat-long or geo information for value of annotation body.'),
(215,1,6,'radio','radio','UI: Render a CHOICE as a set of RADIO BUTTONS.'),
(216,1,6,'checkbox','checkbox','UI: Render a CHOICE as a set of CHECK BOXES.'),
(217,1,6,'capturemodel','captureModel','UI: Render an additional capture model.'),
(218,1,6,'button','button','UI: Render a CHOICE as a set of BUTTONS.'),
(219,1,6,'boxdraw','boxdraw','UI: Draw a BOX to capture #xywh values for a selector.'),
(220,1,6,'ellipse','ellipse','UI: Draw an ELLIPSE to capture an SVG path for a selector.'),
(221,1,6,'svg','svg','UI: Draw a freehand SVG path for a selector.'),
(222,1,6,'polygon','polygon','UI: Draw a POLYGON to capture an SVG path for a selector.'),
(223,1,6,'pin','pin','UI: Drop a pin for a selector.'),
(224,1,6,'nullableCaptureModel','nullableCaptureModel','UI: nullable capture model. Render options, following inputOptions, with the possibility of not following through to the linked capture model.'),
(225,1,6,'fallback_autocomplete','fallback_autocomplete','UI: Render an Autocomplete field to capture input for value of annotation body, and fallback to additional input methods.'),
(226,1,6,'autocomplete','autocomplete','UI: Render an Autocomplete field to capture input for value of annotation body.'),
(227,1,6,'fallback_boolean','fallback_boolean','UI: Boolean input, and fallback to additional input methods on True.'),
(228,1,6,'fallbackOptions','fallbackOptions','UI: Generic fallback between additional input methods described via ui:inputOptions.'),
(229,1,6,'group','group','Capture model object is a group, comprising one or more capture model elements. '),
(230,1,6,'element','element','Capture model object is an element, i.e. a single data capture element (form field, picker, etc.)'),
(231,1,7,'subClassOf','subClassOf','Indicates membership of a class'),
(232,1,7,'subPropertyOf','subPropertyOf','Indicates specialization of properties'),
(233,1,7,'comment','comment','Use this for descriptions'),
(234,1,7,'label','label','Provides a human-readable version of a resource name.'),
(235,1,7,'domain','domain','A domain class for a property type'),
(236,1,7,'range','range','A range class for a property type'),
(237,1,7,'seeAlso','seeAlso','A resource that provides information about the subject resource'),
(238,1,7,'isDefinedBy','isDefinedBy','Indicates the namespace of a resource'),
(239,1,7,'member','member','a member of a container'),
(240,1,8,'hasSequences','hasSequences',NULL),
(241,1,8,'hasRanges','hasRanges',NULL),
(242,1,8,'hasImageAnnotations','hasImageAnnotations',NULL),
(243,1,8,'hasAnnotations','hasAnnotations',NULL),
(244,1,8,'hasCollections','hasCollections',NULL),
(245,1,8,'attributionLabel','attributionLabel','A string containing an attribution description that must be displayed when using the resource'),
(246,1,8,'hasLists','hasLists',NULL),
(247,1,8,'hasManifests','hasManifests',NULL),
(248,1,8,'hasCanvases','hasCanvases',NULL),
(249,1,8,'hasContentLayer','hasContentLayer','A link from a Range to a Layer that provides the content resources of that Range'),
(250,1,8,'viewingHint','viewingHint','A hint to a user agent as to how to render the resource'),
(251,1,8,'metadataLabels','metadataLabels','An rdf:List of label/value pairs providing descriptive metadata about the resource, intended for human audience'),
(252,1,8,'hasStartCanvas','hasStartCanvas','A link from a Manifest or Sequence to the Canvas that the rendering agent should initialize their view with.'),
(253,1,8,'viewingDirection','viewingDirection','References the sc:ViewingDirection that defines the direction that the resource should be viewed in'),
(254,1,9,'tile','tile',NULL),
(255,1,9,'scaleFactor','scaleFactor',NULL),
(256,1,9,'size','size',NULL),
(257,1,9,'format','format',NULL),
(258,1,9,'quality','quality',NULL),
(259,1,9,'supports','supports',NULL),
(260,1,10,'exifdata','Exif data','An Exif IFD data entry'),
(261,1,10,'tag_number','Tag number','The Exif tag number'),
(262,1,10,'tagid','Tag ID','The Exif tag number with context prefix, such as IFD type or maker name'),
(263,1,10,'datatype','Data Type','The Exif field data type, such as ascii, byte, short etc.'),
(264,1,10,'length','Length','Length of an object. Could be a subProperty of other general schema.'),
(265,1,10,'width','Width','Width of an object'),
(266,1,10,'height','Height','Height of an object'),
(267,1,10,'resolution','Resolution','a rational number representing a resolution. Could be a subProperty of other general schema.'),
(268,1,10,'meter','Meter','A length with unit of meter'),
(269,1,10,'mm','Milimeter','A length with unit of mm'),
(270,1,10,'seconds','Seconds','a mesurement of time length with unit of second'),
(271,1,10,'date','Date','a date information. Usually saved as YYYY:MM:DD (HH:MM:SS) format in Exif data, but represented here as W3C-DTF format'),
(272,1,10,'subseconds','Subseconds','A tag used to record fractions of seconds for a date property'),
(273,1,10,'geo','Geometric data','Geometric data such as latitude, longitude and altitude. Usually saved as rational number.'),
(274,1,10,'_unknown','Unknown tag','An Exif tag whose meaning is not known'),
(275,1,10,'exifAttribute','Exif Attribute','A property that connects an IFD to one of its entries. Super property which integrates all Exif tags.'),
(276,1,10,'dateAndOrTime','Date and/or Time','An attribute relating to Date and/or Time'),
(277,1,10,'gpsInfo','GPS Info','An attribute relating to GPS information'),
(278,1,10,'ifdPointer','IFD Pointer','A tag that refers a child IFD'),
(279,1,10,'imageConfig','Image Config','An attribute relating to Image Configuration'),
(280,1,10,'imageDataCharacter','Image Data Character','An attribute relating to image data characteristics'),
(281,1,10,'imageDataStruct','Image Data Structure','An attribute relating to image data structure'),
(282,1,10,'interopInfo','Interoperability Info','An attribute relating to Interoperability. Tags stored in\nInteroperability IFD may be defined dependently to each Interoperability rule.'),
(283,1,10,'pictTaking','PictTaking','An attribute relating to Picture-Taking Conditions'),
(284,1,10,'pimInfo','PIM Info','An attribute relating to print image matching'),
(285,1,10,'recOffset','Recording Offset','An attribute relating to recording offset'),
(286,1,10,'relatedFile','Related File','Tag Relating to Related File Information'),
(287,1,10,'userInfo','User Info','An attribute relating to User Information'),
(288,1,10,'versionInfo','Version Info','An attribute relating to Version'),
(289,1,10,'imageWidth','ImageWidth','Image width. The number of columns of image data, equal to the number of pixels per row. In JPEG compressed data a JPEG marker is used instead of this tag.'),
(290,1,10,'imageLength','ImageLength','Image height. The number of rows of image data. In JPEG compressed data a JPEG marker is used.'),
(291,1,10,'bitsPerSample','BitsPerSample','The number of bits per image component. In this standard each component of the image is 8 bits, so the value for this tag is 8. See also SamplesPerPixel. In JPEG compressed data a JPEG marker is used instead of this tag.'),
(292,1,10,'compression','Compression','The compression scheme used for the image data. When a primary image is JPEG compressed, this designation is not necessary and is omitted. When thumbnails use JPEG compression, this tag value is set to 6.'),
(293,1,10,'photometricInterpretation','PhotometricInterpretation','Pixel composition. In JPEG compressed data a JPEG marker is used instead of this tag.'),
(294,1,10,'imageDescription','ImageDescription','A character string giving the title of the image. It may be a comment such as \"1988 company picnic\" or the like. Two-byte character codes cannot be used. When a 2-byte code is necessary, the Exif Private tag UserComment is to be used.'),
(295,1,10,'make','Make','Manufacturer of image input equipment'),
(296,1,10,'model','Model','Model of image input equipment'),
(297,1,10,'stripOffsets','StripOffsets','For each strip, the byte offset of that strip. With JPEG compressed data this designation is not needed and is omitted.'),
(298,1,10,'orientation','Orientation','The image orientation viewed in terms of rows and columns.'),
(299,1,10,'samplesPerPixel','SamplesPerPixel','The number of components per pixel. Since this standard applies to RGB and YCbCr images, the value set for this tag is 3. In JPEG compressed data a JPEG marker is used instead of this tag.'),
(300,1,10,'rowsPerStrip','RowsPerStrip','The number of rows per strip. This is the number of rows in the image of one strip when an image is divided into strips. With JPEG compressed data this designation is not needed and is omitted.'),
(301,1,10,'stripByteCounts','StripByteCounts','The total number of bytes in each strip. With JPEG compressed data this designation is not needed and is omitted.'),
(302,1,10,'xResolution','XResolution','The number of pixels per ResolutionUnit in the ImageWidth direction. When the image resolution is unknown, 72 [dpi] is designated.'),
(303,1,10,'yResolution','YResolution','The number of pixels per ResolutionUnit in the ImageLength direction. The same value as XResolution is designated.'),
(304,1,10,'planarConfiguration','PlanarConfiguration','Indicates whether pixel components are recorded in chunky or planar format. In JPEG compressed files a JPEG marker is used instead of this tag. If this field does not exist, the TIFF default of 1 (chunky) is assumed.'),
(305,1,10,'resolutionUnit','ResolutionUnit','The unit for measuring XResolution and YResolution. The same unit is used for both XResolution and YResolution. If the image resolution in unknown, 2 (inches) is designated.'),
(306,1,10,'transferFunction','TransferFunction','A transfer function for the image, described in tabular style. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).'),
(307,1,10,'software','Software','The name and version of the software or firmware of the camera or image input device used to generate the image.'),
(308,1,10,'dateTime','DateTime','The date and time of image creation. In this standard it is the date and time the file was changed.'),
(309,1,10,'artist','Artist','Person who created the image'),
(310,1,10,'whitePoint','WhitePoint','The chromaticity of the white point of the image. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).'),
(311,1,10,'primaryChromaticities','PrimaryChromaticities','The chromaticity of the three primary colors of the image. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).'),
(312,1,10,'jpegInterchangeFormat','JPEGInterchangeFormat','The offset to the start byte (SOI) of JPEG compressed thumbnail data. This is not used for primary image JPEG data.'),
(313,1,10,'jpegInterchangeFormatLength','JPEGInterchangeFormatLength','The number of bytes of JPEG compressed thumbnail data. This is not used for primary image JPEG data.'),
(314,1,10,'yCbCrCoefficients','YCbCrCoefficients','The matrix coefficients for transformation from RGB to YCbCr image data.'),
(315,1,10,'yCbCrSubSampling','YCbCrSubSampling','The sampling ratio of chrominance components in relation to the luminance component. In JPEG compressed data a JPEG marker is used instead of this tag.'),
(316,1,10,'yCbCrPositioning','YCbCrPositioning','The position of chrominance components in relation to the luminance component. This field is designated only for JPEG compressed data or uncompressed YCbCr data.'),
(317,1,10,'referenceBlackWhite','ReferenceBlackWhite','The reference black point value and reference white point value. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability these conditions.'),
(318,1,10,'copyright','Copyright','Copyright information. In this standard the tag is used to indicate both the photographer and editor copyrights. It is the copyright notice of the person or organization claiming rights to the image.'),
(319,1,10,'exif_IFD_Pointer','Exif IFD Pointer','A pointer to the Exif IFD, which is a set of tags for recording Exif-specific attribute information.'),
(320,1,10,'gpsInfo_IFD_Pointer','GPSInfo IFD Pointer','A pointer to the GPS IFD, which is a set of tags for recording GPS information.'),
(321,1,10,'exposureTime','ExposureTime','Exposure time, given in seconds (sec).'),
(322,1,10,'fNumber','FNumber','F number'),
(323,1,10,'exposureProgram','ExposureProgram','The class of the program used by the camera to set exposure when the picture is taken.'),
(324,1,10,'spectralSensitivity','SpectralSensitivity','Indicates the spectral sensitivity of each channel of the camera used. The tag value is an ASCII string compatible with the standard developed by the ASTM Technical committee.'),
(325,1,10,'isoSpeedRatings','ISOSpeedRatings','Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.'),
(326,1,10,'oecf','OECF','Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524. OECF is the relationship between the camera optical input and the image values.'),
(327,1,10,'exifVersion','ExifVersion','Exif Version'),
(328,1,10,'dateTimeOriginal','DateTimeOriginal','The date and time when the original image data was generated. For a DSC the date and time the picture was taken are recorded.'),
(329,1,10,'dateTimeDigitized','DateTimeDigitized','The date and time when the image was stored as digital data. If, for example, an image was captured by DSC and at the same time the file was recorded, then the DateTimeOriginal and DateTimeDigitized will have the same contents.'),
(330,1,10,'componentsConfiguration','ComponentsConfiguration','Information specific to compressed data. The channels of each component are arranged in order from the 1st component to the 4th. For uncompressed data the data arrangement is given in the PhotometricInterpretation tag. However, since PhotometricInterpretation can only express the order of Y,Cb and Cr, this tag is provided for cases when compressed data uses components other than Y, Cb, and Cr and to enable support of other sequences.'),
(331,1,10,'compressedBitsPerPixel','CompressedBitsPerPixel','Information specific to compressed data. The compression mode used for a compressed image is indicated in unit bits per pixel.'),
(332,1,10,'shutterSpeedValue','ShutterSpeedValue','Shutter speed. The unit is the APEX (Additive System of Photographic Exposure) setting'),
(333,1,10,'apertureValue','ApertureValue','The lens aperture. The unit is the APEX value.'),
(334,1,10,'brightnessValue','BrightnessValue','The value of brightness. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99. Note that if the numerator of the recorded value is FFFFFFFF.H, Unknown shall be indicated.'),
(335,1,10,'exposureBiasValue','ExposureBiasValue','The exposure bias. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99.'),
(336,1,10,'maxApertureValue','MaxApertureValue','The smallest F number of the lens. The unit is the APEX value. Ordinarily it is given in the range of 00.00 to 99.99, but it is not limited to this range.'),
(337,1,10,'subjectDistance','SubjectDistance','The distance to the subject, given in meters. Note that if the numerator of the recorded value is FFFFFFFF.H, Infinity shall be indicated; and if the numerator is 0, Distance unknown shall be indicated.'),
(338,1,10,'meteringMode','MeteringMode','Metering mode, such as CenterWeightedAverage, Spot, MultiSpot,Pattern, Partial etc.'),
(339,1,10,'lightSource','LightSource','Light source such as Daylight, Tungsten, Flash etc.'),
(340,1,10,'flash','Flash','The status of flash when the image was shot.'),
(341,1,10,'focalLength','FocalLength','The actual focal length of the lens, in mm. Conversion is not made to the focal length of a 35 mm film camera.'),
(342,1,10,'subjectArea','SubjectArea','The location and area of the main subject in the overall scene.'),
(343,1,10,'makerNote','MakerNote','Manufacturer notes'),
(344,1,10,'userComment','UserComment','A tag for Exif users to write keywords or comments on the image besides those in ImageDescription, and without the character code limitations of the ImageDescription tag. The character code used in the UserComment tag is identified based on an ID code in a fixed 8-byte area at the start of the tag data area.'),
(345,1,10,'subSecTime','SubSecTime','DateTime subseconds'),
(346,1,10,'subSecTimeOriginal','SubSecTimeOriginal','DateTimeOriginal subseconds'),
(347,1,10,'subSecTimeDigitized','SubSecTimeDigitized','DateTimeDigitized subseconds'),
(348,1,10,'flashpixVersion','FlashpixVersion','The Flashpix format version supported by a FPXR file. If the FPXR function supports Flashpix format Ver. 1.0, this is indicated similarly to ExifVersion by recording \"0100\" as 4-byte ASCII.'),
(349,1,10,'colorSpace','ColorSpace','The color space information tag (ColorSpace) is always recorded as the color space specifier. Normally sRGB (=1) is used to define the color space based on the PC monitor conditions and environment.'),
(350,1,10,'pixelXDimension','PixelXDimension','Information specific to compressed data. When a compressed file is recorded, the valid width of the meaningful image shall be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file.'),
(351,1,10,'pixelYDimension','PixelYDimension','Information specific to compressed data. When a compressed file is recorded, the valid height of the meaningful image shall be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file. Since data padding is unnecessary in the vertical direction, the number of lines recorded in this valid image height tag will in fact be the same as that recorded in the SOF.'),
(352,1,10,'relatedSoundFile','RelatedSoundFile','Related audio file'),
(353,1,10,'interoperability_IFD_Pointer','Interoperability IFD Pointer','A pointer to the Interoperability IFD, which is composed of tags storing the information to ensure the Interoperability'),
(354,1,10,'flashEnergy','FlashEnergy','The strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds (BCPS).'),
(355,1,10,'spatialFrequencyResponse','SpatialFrequencyResponse','This tag records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.'),
(356,1,10,'focalPlaneXResolution','FocalPlaneXResolution','The number of pixels in the image width (X) direction per FocalPlaneResolutionUnit on the camera focal plane.'),
(357,1,10,'focalPlaneYResolution','FocalPlaneYResolution','The number of pixels in the image height (Y) direction per FocalPlaneResolutionUnit on the camera focal plane.'),
(358,1,10,'focalPlaneResolutionUnit','FocalPlaneResolutionUnit','The unit for measuring FocalPlaneXResolution and FocalPlaneYResolution. This value is the same as the ResolutionUnit.'),
(359,1,10,'subjectLocation','SubjectLocation','The location of the main subject in the scene. The value of this tag represents the pixel at the center of the main subject relative to the left edge, prior to rotation processing as per the Rotation tag. The first value indicates the X column number and second indicates the Y row number.'),
(360,1,10,'exposureIndex','ExposureIndex','The exposure index selected on the camera or input device at the time the image is captured.'),
(361,1,10,'sensingMethod','SensingMethod','The image sensor type on the camera or input device, such as One-chip color area sensor etc.'),
(362,1,10,'fileSource','FileSource','The image source. If a DSC recorded the image, this tag value of this tag always be set to 3, indicating that the image was recorded on a DSC.'),
(363,1,10,'sceneType','SceneType','The type of scene. If a DSC recorded the image, this tag value shall always be set to 1, indicating that the image was directly photographed.'),
(364,1,10,'cfaPattern','CFAPattern','The color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods.'),
(365,1,10,'customRendered','CustomRendered','The use of special processing on image data, such as rendering geared to output. When special processing is performed, the reader is expected to disable or minimize any further processing.'),
(366,1,10,'exposureMode','ExposureMode','the exposure mode set when the image was shot. In auto-bracketing mode, the camera shoots a series of frames of the same scene at different exposure settings.'),
(367,1,10,'whiteBalance','WhiteBalance','The white balance mode set when the image was shot.'),
(368,1,10,'digitalZoomRatio','DigitalZoomRatio','The digital zoom ratio when the image was shot. If the numerator of the recorded value is 0, this indicates that digital zoom was not used.'),
(369,1,10,'focalLengthIn35mmFilm','FocalLengthIn35mmFilm','The equivalent focal length assuming a 35mm film camera, in mm. A value of 0 means the focal length is unknown. Note that this tag differs from the FocalLength tag.'),
(370,1,10,'sceneCaptureType','SceneCaptureType','The type of scene that was shot. It can also be used to record the mode in which the image was shot, such as Landscape, Portrait etc. Note that this differs from the scene type (SceneType) tag.'),
(371,1,10,'gainControl','GainControl','The degree of overall image gain adjustment.'),
(372,1,10,'contrast','Contrast','The direction of contrast processing applied by the camera when the image was shot.'),
(373,1,10,'saturation','Saturation','The direction of saturation processing applied by the camera when the image was shot.'),
(374,1,10,'sharpness','Sharpness','The direction of sharpness processing applied by the camera when the image was shot.'),
(375,1,10,'deviceSettingDescription','DeviceSettingDescription','Information on the picture-taking conditions of a particular camera model. The tag is used only to indicate the picture-taking conditions in the reader.'),
(376,1,10,'subjectDistanceRange','SubjectDistanceRange','The distance to the subject, such as Macro, Close View or Distant View.'),
(377,1,10,'imageUniqueID','ImageUniqueID','An identifier assigned uniquely to each image. It is recorded as an ASCII string equivalent to hexadecimal notation and 128-bit fixed length.'),
(378,1,10,'gpsVersionID','GPSVersionID','The version of GPSInfoIFD. The version is given as 2.2.0.0. This tag is mandatory when GPSInfo tag is present.'),
(379,1,10,'gpsLatitudeRef','GPSLatitudeRef','Indicates whether the latitude is north or south latitude. The ASCII value \'N\' indicates north latitude, and \'S\' is south latitude.'),
(380,1,10,'gpsLatitude','GPSLatitude','The latitude, expressed as three values giving the degrees, minutes, and seconds, respectively.'),
(381,1,10,'gpsLongitudeRef','GPSLongitudeRef','Indicates whether the longitude is east or west longitude. ASCII \'E\' indicates east longitude, and \'W\' is west longitude.'),
(382,1,10,'gpsLongitude','GPSLongitude','The longitude, expressed as three values giving the degrees, minutes, and seconds, respectively.'),
(383,1,10,'gpsAltitudeRef','GPSAltitudeRef','Indicates the altitude used as the reference altitude. If the reference is sea level and the altitude is above sea level, 0 is given. If the altitude is below sea level, a value of 1 is given and the altitude is indicated as an absolute value in the GPSAltitude tag. The reference unit is meters.'),
(384,1,10,'gpsAltitude','GPSAltitude','The altitude based on the reference in GPSAltitudeRef. Altitude is expressed as one RATIONAL value. The reference unit is meters.'),
(385,1,10,'gpsTimeStamp','GPSTimeStamp','The time as UTC (Coordinated Universal Time). TimeStamp is expressed as three RATIONAL values giving the hour, minute, and second.'),
(386,1,10,'gpsSatellites','GPSSatellites','The GPS satellites used for measurements. This tag can be used to describe the number of satellites, their ID number, angle of elevation, azimuth, SNR and other information in ASCII notation. The format is not specified. If the GPS receiver is incapable of taking measurements, value of the tag shall be set to NULL.'),
(387,1,10,'gpsStatus','GPSStatus','The status of the GPS receiver when the image is recorded. \'A\' means measurement is in progress, and \'V\' means the measurement is Interoperability.'),
(388,1,10,'gpsMeasureMode','GPSMeasureMode','The GPS measurement mode. \'2\' means two-dimensional measurement and \'3\' means three-dimensional measurement is in progress.'),
(389,1,10,'gpsDOP','GPSDOP','The GPS DOP (data degree of precision). An HDOP value is written during two-dimensional measurement, and PDOP during three-dimensional measurement.'),
(390,1,10,'gpsSpeedRef','GPSSpeedRef','The unit used to express the GPS receiver speed of movement. \'K\' \'M\' and \'N\' represents kilometers per hour, miles per hour, and knots.'),
(391,1,10,'gpsSpeed','GPSSpeed','The speed of GPS receiver movement.'),
(392,1,10,'gpsTrackRef','GPSTrackRef','The reference for giving the direction of GPS receiver movement. \'T\' denotes true direction and \'M\' is magnetic direction.'),
(393,1,10,'gpsTrack','GPSTrack','The direction of GPS receiver movement. The range of values is from 0.00 to 359.99.'),
(394,1,10,'gpsImgDirectionRef','GPSImgDirectionRef','The reference for giving the direction of the image when it is captured. \'T\' denotes true direction and \'M\' is magnetic direction.'),
(395,1,10,'gpsImgDirection','GPSImgDirection','The direction of the image when it was captured. The range of values is from 0.00 to 359.99.'),
(396,1,10,'gpsMapDatum','GPSMapDatum','The geodetic survey data used by the GPS receiver. If the survey data is restricted to Japan, the value of this tag is TOKYO or WGS-84. If a GPS Info tag is recorded, it is strongly recommended that this tag be recorded.'),
(397,1,10,'gpsDestLatitudeRef','GPSDestLatitudeRef','Reference for latitude of destination'),
(398,1,10,'gpsDestLatitude','GPSDestLatitude','Latitude of destination, expressed as three values giving the degrees, minutes, and seconds, respectively.'),
(399,1,10,'gpsDestLongitudeRef','GPSDestLongitudeRef','Reference for longitude of destination'),
(400,1,10,'gpsDestLongitude','GPSDestLongitude','Longitude of destination, expressed as three values giving the degrees, minutes, and seconds, respectively.'),
(401,1,10,'gpsDestBearingRef','GPSDestBearingRef','Indicates the reference used for giving the bearing to the destination point. \'T\' denotes true direction and \'M\' is magnetic direction.'),
(402,1,10,'gpsDestBearing','GPSDestBearing','The bearing to the destination point. The range of values is from 0.00 to 359.99.'),
(403,1,10,'gpsDestDistanceRef','GPSDestDistanceRef','Indicates the unit used to express the distance to the destination point. \'K\', \'M\' and \'N\' represent kilometers, miles and knots.'),
(404,1,10,'gpsDestDistance','GPSDestDistance','The distance to the destination point.'),
(405,1,10,'gpsProcessingMethod','GPSProcessingMethod','A character string recording the name of the method used for location finding. The first byte indicates the character code used, and this is followed by the name of the method.'),
(406,1,10,'gpsAreaInformation','GPSAreaInformation','A character string recording the name of the GPS area. The first byte indicates the character code used, and this is followed by the name of the GPS area.'),
(407,1,10,'gpsDateStamp','GPSDateStamp','date and time information relative to UTC (Coordinated Universal Time). The record format is \"YYYY:MM:DD\" while converted to W3C-DTF to use in RDF'),
(408,1,10,'gpsDifferential','GPSDifferential','Indicates whether differential correction is applied to the GPS receiver.'),
(409,1,10,'interoperabilityIndex','InteroperabilityIndex','Indicates the identification of the Interoperability rule. R98 = conforming to R98 file specification of Recommended Exif Interoperability Rules (ExifR98) or to DCF basic file stipulated by Design Rule for Camera File System. THM = conforming to DCF thumbnail file stipulated by Design rule for Camera File System.'),
(410,1,10,'interoperabilityVersion','InteroperabilityVersion','Interoperability Version'),
(411,1,10,'relatedImageFileFormat','RelatedImageFileFormat','Related image file format'),
(412,1,10,'relatedImageWidth','RelatedImageWidth','Related image width'),
(413,1,10,'relatedImageLength','RelatedImageLength','Related image length'),
(414,1,10,'printImageMatching_IFD_Pointer','PrintImageMatching IFD Pointer','A pointer to the print image matching IFD'),
(415,1,10,'pimContrast','PrintIM Contrast','Contrast info for print image matching'),
(416,1,10,'pimBrightness','PrintIM Brightness','Brightness info for print image matching'),
(417,1,10,'pimColorBalance','PrintIM ColorBalance','ColorBalance info for print image matching'),
(418,1,10,'pimSaturation','PrintIM Saturation','Saturation info for print image matching'),
(419,1,10,'pimSharpness','PrintIM Sharpness','Sharpness info for print image matching'),
(420,1,11,'sourceDateStart','sourceDateStart','The start timestamp of the interval over which the Source resource should be interpreted as being applicable to the Annotation.'),
(421,1,11,'suffix','suffix','The snippet of text that occurs immediately after the text which is being selected.'),
(422,1,11,'styledBy','styledBy','A reference to a Stylesheet that should be used to apply styles to the Annotation rendering.'),
(423,1,11,'hasTarget','hasTarget','The relationship between an Annotation and its Target.'),
(424,1,11,'cachedSource','cachedSource','A object of the relationship is a copy of the Source resources representation, appropriate for the Annotation.'),
(425,1,11,'hasEndSelector','hasEndSelector','The relationship between a RangeSelector and the Selector that describes the end position of the range. '),
(426,1,11,'textDirection','textDirection','The direction of the text of the subject resource. There MUST only be one text direction associated with any given resource.'),
(427,1,11,'processingLanguage','processingLanguage','The object of the property is the language that should be used for textual processing algorithms when dealing with the content of the resource, including hyphenation, line breaking, which font to use for rendering and so forth.  The value must follow the recommendations of BCP47.'),
(428,1,11,'canonical','canonical','A object of the relationship is the canonical IRI that can always be used to deduplicate the Annotation, regardless of the current IRI used to access the representation.'),
(429,1,11,'sourceDateEnd','sourceDateEnd','The end timestamp of the interval over which the Source resource should be interpreted as being applicable to the Annotation.'),
(430,1,11,'hasPurpose','hasPurpose','The purpose served by the resource in the Annotation.'),
(431,1,11,'bodyValue','bodyValue','The object of the predicate is a plain text string to be used as the content of the body of the Annotation.  The value MUST be an  xsd:string  and that data type MUST NOT be expressed in the serialization. Note that language MUST NOT be associated with the value either as a language tag, as that is only available for  rdf:langString .\n  '),
(432,1,11,'styleClass','styleClass','The name of the class used in the CSS description referenced from the Annotation that should be applied to the Specific Resource.'),
(433,1,11,'hasStartSelector','hasStartSelector','The relationship between a RangeSelector and the Selector that describes the start position of the range. '),
(434,1,11,'hasScope','hasScope','The scope or context in which the resource is used within the Annotation.'),
(435,1,11,'hasState','hasState','The relationship between the ResourceSelection, or its subclass SpecificResource, and a State resource. Please note that the domain ( oa:ResourceSelection ) is not used directly in the Web Annotation model.'),
(436,1,11,'exact','exact','The object of the predicate is a copy of the text which is being selected, after normalization.'),
(437,1,11,'hasSelector','hasSelector','The object of the relationship is a Selector that describes the segment or region of interest within the source resource.  Please note that the domain ( oa:ResourceSelection ) is not used directly in the Web Annotation model.'),
(438,1,11,'hasBody','hasBody','The object of the relationship is a resource that is a body of the Annotation.'),
(439,1,11,'motivatedBy','motivatedBy','The relationship between an Annotation and a Motivation that describes the reason for the Annotations creation.'),
(440,1,11,'end','end','The end property is used to convey the 0-based index of the end position of a range of content.'),
(441,1,11,'refinedBy','refinedBy','The relationship between a Selector and another Selector or a State and a Selector or State that should be applied to the results of the first to refine the processing of the source resource. '),
(442,1,11,'start','start','The start position in a 0-based index at which a range of content is selected from the data in the source resource.'),
(443,1,11,'renderedVia','renderedVia','A system that was used by the application that created the Annotation to render the resource.'),
(444,1,11,'sourceDate','sourceDate','The timestamp at which the Source resource should be interpreted as being applicable to the Annotation.'),
(445,1,11,'via','via','A object of the relationship is a resource from which the source resource was retrieved by the providing system.'),
(446,1,11,'annotationService','annotationService','The object of the relationship is the end point of a service that conforms to the annotation-protocol, and it may be associated with any resource.  The expectation of asserting the relationship is that the object is the preferred service for maintaining annotations about the subject resource, according to the publisher of the relationship.\n\n  This relationship is intended to be used both within Linked Data descriptions and as the  rel  type of a Link, via HTTP Link Headers rfc5988 for binary resources and in HTML <link> elements.  For more information about these, please see the Annotation Protocol specification annotation-protocol.\n  '),
(447,1,11,'prefix','prefix','The object of the property is a snippet of content that occurs immediately before the content which is being selected by the Selector.'),
(448,1,11,'hasSource','hasSource','The resource that the ResourceSelection, or its subclass SpecificResource, is refined from, or more specific than. Please note that the domain ( oa:ResourceSelection ) is not used directly in the Web Annotation model.');
/*!40000 ALTER TABLE `property` ENABLE KEYS */;
UNLOCK TABLES;
