server {
  listen 443 ssl;
  server_name madoc.local;
  ssl_certificate /certs/local-cert.pem;
  ssl_certificate_key /certs/local-key.pem;
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_pass http://127.0.0.1:8080;
  }
}
