worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log warn;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  access_log /var/log/nginx/access.log;
  proxy_cache_path /var/cache/nginx/asset levels=1:2 keys_zone=asset_cache:10m max_size=100m inactive=60m use_temp_path=off;
  proxy_cache_path /var/cache/nginx/media levels=1:2 keys_zone=media_cache:10m max_size=10g inactive=60m use_temp_path=off;
  proxy_cache_path /var/cache/nginx/token_responses keys_zone=token_responses:1m max_size=2m;
  server_names_hash_bucket_size 64;
  sendfile on;
  gzip on;
  include /etc/nginx/conf.d/*.conf;
}
