# syntax=docker/dockerfile:1.6
ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-bullseye

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /home/node/app

RUN npm install -g pm2@5.2.2 ts-node

COPY ./package.json /home/node/app/package.json
COPY ./pnpm-lock.yaml /home/node/app/pnpm-lock.yaml
COPY ./npm /home/node/app/npm

RUN corepack enable
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY ./schemas /home/node/app/schemas
COPY ./src /home/node/app/src
COPY ./ecosystem.config.cjs /home/node/app/ecosystem.config.cjs
COPY ./tsconfig.json /home/node/app/tsconfig.json
COPY ./tsconfig.frontend.json /home/node/app/tsconfig.frontend.json
COPY ./migrations /home/node/app/migrations
COPY ./config.json /home/node/app/config.json
COPY ./generate-schemas.js /home/node/app/generate-schemas.js
COPY ./postcss.config.js /home/node/app/postcss.config.js
COPY ./tailwind.config.js /home/node/app/tailwind.config.js
COPY ./translations /home/node/app/translations
COPY ./schemas /home/node/app/schemas
COPY ./themes /home/node/app/themes
COPY ./vite /home/node/app/vite
COPY ./entrypoint /home/node/app/entrypoint

ENV SERVER_PORT=3000
ENV DATABASE_HOST=localhost
ENV DATABASE_NAME=postgres
ENV DATABASE_PORT=5400
ENV DATABASE_USER=postgres
ENV DATABASE_SCHEMA=public
ENV DATABASE_PASSWORD=postgres
ENV NODE_ENV=development
ENV API_GATEWAY_HOST=http://gateway

RUN pnpm run build:vite

EXPOSE 3000
EXPOSE 3001
EXPOSE 9230

CMD ["pnpm", "dev"]
