# syntax=docker/dockerfile:1.6
FROM node:24-bullseye
ENV PNPM_HOME=/pnpm PATH=/pnpm:$PATH
RUN corepack enable
WORKDIR /workspace
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY patches ./patches
COPY services/madoc-ts/package.json ./services/madoc-ts/package.json
COPY services/madoc-ts/npm ./services/madoc-ts/npm
COPY services/config-service/package.json ./services/config-service/package.json
COPY services/tasks-api/package.json ./services/tasks-api/package.json
COPY services/storage-api/package.json ./services/storage-api/package.json
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --filter madoc-ts --frozen-lockfile
COPY services/madoc-ts ./services/madoc-ts
RUN mkdir -p /home/node && ln -s /workspace/services/madoc-ts /home/node/app
WORKDIR /home/node/app
EXPOSE 3088 3089
CMD ["pnpm", "dev:vite"]
