allowBuilds:
  '@swc/core': true
  core-js: false
  esbuild: true
  msgpackr-extract: true
  sharp: true
  typesense-instantsearch-adapter: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - iiif-browser@2.2.5

overrides:
  '@atlas-viewer/atlas': 3.2.3
  '@atlas-viewer/iiif-image-api': 2.2.2
  '@babel/core': ^7.29.0
  '@babel/generator': ^7.29.0
  '@babel/runtime': ^7.28.6
  '@babel/types': ^7.29.0
  '@iiif/helpers': ^1.6.1
  '@iiif/vocabulary': 1.0.31
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  deepmerge: 4.3.1
  dnd-multi-backend: 9.0.0
  formik: ^2.2.9
  html-entities: 1.4.0
  iiif-browser: 2.2.5
  immer: ^9
  immutable: 3.8.2
  popmotion: ^8.7.6
  react: 19.2.8
  react-dnd: ^16.0.1
  react-dnd-multi-backend: ^9.0.0
  react-dom: 19.2.8
  react-i18next: ^11.18.6
  react-reconciler: 0.33.0
  slonik-sql-tag-raw: 1.0.2
  styled-components: 6.3.8
  ws: ^8.21.3

peerDependencyRules:
  allowedVersions:
    prosemirror-tables: ^1.8.5
    slonik: ^23.0.0
