<?php

namespace i18n\Loader;

use BabDev\Transifex\Transifex;
use Zend\I18n\Translator\TextDomain;

/**
 * A {@link TextDomain} loader that extracts a {@code project} and {@code resource}
 * identifier from the translation context and uses it as Transifex key.
 *
 * Class TransifexMessageLoader
 */
class TransifexResourceMessageLoader extends AbstractTransifexMessageLoader
{
    /**
     * The name of the message bundle file generated by Transifex.
     */
    const MESSAGE_BUNDLE_RESOURCE = 'messages.en_GB.po';

    public function identifyResource($locale, $textDomain)
    {
        $parts = explode(':', $textDomain);

        if (2 !== count($parts)) {
            return null;
        }

        return $parts;
    }
}
