<?php

namespace IIIFStorage\Media;

use IIIFStorage\Repository\ManifestRepository;
use IIIFStorage\Utility\PropertyIdSaturator;
use Omeka\Api\Manager;
use Omeka\Api\Representation\ItemRepresentation;
use Omeka\Api\Representation\ValueRepresentation;
use Omeka\Form\Element\ResourceSelect;
use Omeka\Media\Ingester\IngesterInterface;
use Throwable;
use Zend\Form\Element;
use Zend\View\Renderer\PhpRenderer;

class CanvasSnippetIngester extends AbstractIngester implements IngesterInterface
{
    private $api;
    /**
     * @var PropertyIdSaturator
     */
    private $saturator;

    public function __construct(
        Manager $api,
        PropertyIdSaturator $saturator
    ) {
        $this->api = $api;
        $this->saturator = $saturator;
    }

    /**
     * Get a human-readable label for this ingester.
     *
     * @return string
     */
    public function getLabel()
    {
        return 'Canvas snippet';
    }

    /**
     * Get the name of the renderer for media ingested by this ingester
     *
     * @return string
     */
    public function getRenderer()
    {
        return 'iiif-canvas-snippet';
    }

    public function renderFormElements(PhpRenderer $view, array $formElements)
    {
        $elements = parent::renderFormElements($view, $formElements); // TODO: Change the autogenerated stub
        return implode('', [
            $elements,
            '<script>$("body").on(\'click [data-media-type="iiif-canvas-snippet"]\', function () { $("#canvas-select").chosen(chosenOptions); });</script>',
        ]);
    }

    /**
     * @param string $operation either "create" or "update"
     * @return Element[]
     */
    public function getFormElements(string $operation): array
    {
        $canvas = new ResourceSelect('canvas');
        $canvas->setApiManager($this->api);
        $canvas->setAttributes([
            'required' => false,
            'id' => 'canvas-select',
            'class' => 'chosen-select',
            'data-placeholder' => 'Select a canvas', // @translate
            'data-api-base-url' => '/api/items',
        ]);
        $canvas->setOptions([
            'label' => 'Choose canvas', // @translate
            'info' => 'Choose a canvas to be displayed.', // @translate
            'empty_option' => '',
            'resource_value_options' => [
                'resource' => 'items',
                'query' => [
                    'resource_class_id' => $this->saturator->getResourceClassByTerm('sc:Canvas')->id() // @todo get resource class ID dynamically.
                ],
                'option_text_callback' => function (ItemRepresentation $item) {
                    // Get the manifest if possible
                    $manifestLabel = $this->getManifestLabel($item);
                    if ($manifestLabel) {
                        return "$manifestLabel - " . $item->displayTitle();
                    }
                    /** @var ItemRepresentation $item */
                    return $item->displayTitle();
                },
            ],
        ]);

        return [
            $canvas
        ];
    }

    public function getManifestLabel(ItemRepresentation $item): string
    {
        /** @var ValueRepresentation $manifestId */
        $manifestId = $item->value('dcterms:isPartOf');


        if (!$manifestId || !$manifestId->valueResource()) {
            return '';
        }

        try {
            /** @var ItemRepresentation $manifest */
            $manifest = $this->api->read(ManifestRepository::API_TYPE, $manifestId->valueResource()->id())->getContent();
            return $manifest ? $manifest->displayTitle() : '';
        } catch (Throwable $e) {
            return '';
        }
    }
}