<?php

namespace IIIFStorage\Media;

use Digirati\OmekaShared\Utility\PropertyIdSaturator;
use Omeka\Api\Manager;
use Omeka\Api\Representation\ItemRepresentation;
use Omeka\Form\Element\ResourceSelect;
use Omeka\Media\Ingester\IngesterInterface;
use Zend\Form\Element;
use Zend\View\Renderer\PhpRenderer;

class ManifestSnippetIngester extends AbstractIngester implements IngesterInterface
{

    /**
     * @var Manager
     */
    private $api;
    /**
     * @var PropertyIdSaturator
     */
    private $saturator;

    public function __construct(
        Manager $api,
        PropertyIdSaturator $saturator
    ) {
        $this->api = $api;
        $this->saturator = $saturator;
    }

    /**
     * Get a human-readable label for this ingester.
     *
     * @return string
     */
    public function getLabel()
    {
        return 'Manifest snippet';
    }

    /**
     * Get the name of the renderer for media ingested by this ingester
     *
     * @return string
     */
    public function getRenderer()
    {
        return 'iiif-manifest-snippet';
    }

    public function renderFormElements(PhpRenderer $view, array $formElements)
    {
        $elements = parent::renderFormElements($view, $formElements); // TODO: Change the autogenerated stub
        return implode('', [
            $elements,
            '<script>$("body").on(\'click [data-media-type="iiif-manifest-snippet"]\', function () { $("#manifest-select").chosen(chosenOptions); });</script>',
        ]);
    }

    /**
     * @param string $operation either "create" or "update"
     * @return Element[]
     */
    public function getFormElements(string $operation): array
    {
        $manifest = new ResourceSelect('manifest');
        $manifest->setApiManager($this->api);
        $manifest->setAttributes([
            'required' => false,
            'id' => 'manifest-select',
            'class' => 'chosen-select',
            'data-placeholder' => 'Select a manifest', // @translate
            'data-api-base-url' => '/api/items',
        ]);
        $manifest->setOptions([
            'label' => 'Choose manifest', // @translate
            'info' => 'Choose a manifest to be displayed.', // @translate
            'empty_option' => '',
            'resource_value_options' => [
                'resource' => 'items',
                'query' => [
                    'resource_class_id' => $this->saturator->getResourceClassByTerm('sc:Manifest')->id()
                ],
                'option_text_callback' => function ($item) {
                    /** @var ItemRepresentation $item */
                    return $item->displayTitle();
                },
            ],
        ]);

        return [
            $manifest,
        ];
    }
}
