<?php
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):
    ?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
<?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
        <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php $content = trim($this->content); ?>
    <?php if (!$content): ?>
        <a href="/admin/site/s/<?php print $site->slug(); ?>/page/<?php print $page->slug(); ?>">
            <img src="<?php echo $this->assetUrl('hello-madoc.svg'); ?>" alt="Login and add some content" />
        </a>
    <?php else: ?>
        <?php echo $content; ?>
    <?php endif; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
    <?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
