<?php
//$form->setAttribute('action', $this->url('admin/iiif-import', array('action' => 'process')));
//$form->prepare();
//$escapeHtml = $this->plugin('escapeHtml');
//?>
<h2>asdasdasdasd</h2>
<!---->
<?php //echo $this->pageTitle($this->translate('Import An IIIF Collection or Manifest')); ?>
<!---->
<!---->
<?php //echo $this->form()->openTag($form); ?>
<!--    <fieldset id='page-actions'>-->
<!--        <button type="submit">--><?php //echo $this->translate('Next'); ?><!--</button>-->
<!--    </fieldset>-->
<?php //echo $this->formCollection($form, false); ?>
<!---->
<?php //echo $this->form()->closeTag($form); ?>