<?php

namespace i18n\Loader;

class TransifexCoreMessageLoader extends AbstractTransifexMessageLoader
{
    /**
     * The name of the message bundle file generated by.
     */
    const MESSAGE_BUNDLE_RESOURCE = 'base';

    /**
     * @TODO: make this configurable.
     */
    const MESSAGE_BUNDLE_PROJECT = 'omeka-core';

    /**
     * @param string $locale
     * @param string $textDomain
     *
     * @return array|null
     */
    public function identifyResource($locale, $textDomain)
    {
        if ('default' === $textDomain) {
            return [self::MESSAGE_BUNDLE_PROJECT, self::MESSAGE_BUNDLE_RESOURCE];
        }

        return null;
    }
}
