<?php

namespace i18n\Loader;

class TransifexThemeMessageLoader extends AbstractTransifexMessageLoader
{
    /**
     * The name of the message bundle file generated by.
     */
    const MESSAGE_BUNDLE_RESOURCE = 'messagesenpo';

    const MESSAGE_BUNDLE_PROJECT = 'omeka-all';

    public function identifyResource($locale, $textDomain)
    {
        if ('default' === $textDomain) {
            return [self::MESSAGE_BUNDLE_PROJECT, self::MESSAGE_BUNDLE_RESOURCE];
        }

        return null;
    }
}
