name: Madoc TS Docker

on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']
    paths:
      - ".github/workflows/madoc-ts-docker.yaml"
      - "services/madoc-ts/src/**"
      - "services/madoc-ts/migrations/**"
      - "services/madoc-ts/translations/**"
      - "services/madoc-ts/schemas/**"
      - "services/madoc-ts/themes/**"
      - "services/madoc-ts/package.json"
      - "services/madoc-ts/yarn.lock"
      - "services/madoc-ts/Dockerfile"
      - "services/madoc-ts/ecosystem.config.js"
      - "services/madoc-ts/webpack.config.js"
      - "services/madoc-ts/tsconfig.json"

jobs:

  madoc-ts-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/digirati-co-uk/madoc-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SHA to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: services/madoc-ts
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
